Fix compilation with Visual C++ 2015
Wohlhabend-Networks/luabind-deboostified pull request #10
Opened 2022-09-27 17:47 UTC by Supermario1313

2022-09-27 23:06 UTC, Wohlstand commented
Be sure to don't break compilation on other platforms. Gonna verify this as soon as I can.

2022-09-28 00:26 UTC, Wohlstand commented
Okay, I took a look and the reason why I made these lines is that there are build failures happening at some platforms (I don't remind on which), and I made that:
https://github.com/WohlSoft/luabind-deboostified/commit/8274224071513bdc6ee4429bd7619654f4e4683d

You should add the `#ifdef _MSC_VER` macros to use the different variants of this.

2022-09-28 00:29 UTC, Wohlstand requested changes

2022-09-28 00:29 UTC, Wohlstand commented on luabind/out_value_policy.hpp
> +				storage_.template construct<T>();
Please use macros to don't break other builds:
```cpp
#ifdef _MSC_VER
    storage_.template construct<T>();
#else
    storage_.decltype(storage_)::template construct<T>();
#endif

2022-09-28 00:29 UTC, Wohlstand commented on luabind/out_value_policy.hpp
> +				storage_.template construct<T>();
Same as above.

2022-09-28 06:16 UTC, Supermario1313 commented
Fixed. I still wonder what compiler has a problem with this syntax though. From what I've seen on the Internet, it's the standard way of calling a templated function and it compiles without errors on MSVC and Clang.

2022-09-28 08:29 UTC, Wohlstand commented
Don't forget about CLang on other OS and GCC (and various versions of all of them). MSVC is the most annoying because it sometimes a pain at templates features support. Additionally, MSVC fails to get a pointer to the sub-steucture's field when other compilers works just fine.

2022-09-28 08:30 UTC, Wohlstand commented
Okay, I'll merge the thing when I get my PC.

2022-09-28 09:44 UTC, Wohlstand approved these changes
Should be fine now.

2022-09-28 09:44 UTC, merged